/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.rentas;

import java.text.SimpleDateFormat;
import vista.mensajes.Mensajes;
import tr.rentas.Conexion;
import tr.rentas.ManipulaInterfaces;
import tr.rentas.Querys;
import tr.rentas.Validaciones;
import java.util.ArrayList;

/**
 *
 * @author Roy
 */
public class CAltaRentasParametros extends javax.swing.JFrame {
    
    static CAltaRentasParametros pantallaAltaRenta = new CAltaRentasParametros();

    /**
     * Creates new form CAltaRentasParametros
     */
    public CAltaRentasParametros() {
        initComponents();
    }
    
    /*
    validamos campos vacios
    */
    public int validaCamposVacios()
    {
        if (jTRentaActual.getText().equals(""))
        {
            Mensajes.falla(this, "El campo de Renta Actual no debe estar en blanco");
            jTRentaActual.requestFocus();
            return 1;
        }else if (jDFechaRentaActual.getDate() == null)
        {
            Mensajes.falla(this, "El campo de Fecha de Renta Actual no debe estar en blanco");
            jDFechaRentaActual.requestFocus();
            return 1;
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLRPR = new javax.swing.JLabel();
        jLRenActu = new javax.swing.JLabel();
        jTRentaActual = new javax.swing.JTextField();
        jLFeRenActu = new javax.swing.JLabel();
        jDFechaRentaActual = new com.toedter.calendar.JDateChooser();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLRPR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLRPR.setText("Registro de Parametros Rentas");

        jLRenActu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLRenActu.setForeground(new java.awt.Color(51, 51, 51));
        jLRenActu.setText("Renta Actual:");

        jTRentaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRentaActualActionPerformed(evt);
            }
        });
        jTRentaActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTRentaActualKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTRentaActualKeyTyped(evt);
            }
        });

        jLFeRenActu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLFeRenActu.setForeground(new java.awt.Color(51, 51, 51));
        jLFeRenActu.setText("Fecha Renta Actual:");

        jDFechaRentaActual.setDateFormatString("yyyy-MMM-dd");
        jDFechaRentaActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDFechaRentaActualKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDFechaRentaActualKeyTyped(evt);
            }
        });

        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Aceptar.setText("Aceptar");
        Aceptar.setMaximumSize(new java.awt.Dimension(120, 50));
        Aceptar.setMinimumSize(new java.awt.Dimension(120, 50));
        Aceptar.setPreferredSize(new java.awt.Dimension(120, 50));
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        Aceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AceptarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AceptarKeyTyped(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setMaximumSize(new java.awt.Dimension(120, 50));
        Cancelar.setMinimumSize(new java.awt.Dimension(120, 50));
        Cancelar.setPreferredSize(new java.awt.Dimension(120, 50));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        Cancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CancelarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLFeRenActu)
                            .addComponent(jLRenActu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTRentaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jDFechaRentaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLRPR)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLRPR)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRenActu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRentaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLFeRenActu, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jDFechaRentaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTRentaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRentaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRentaActualActionPerformed

    private void jTRentaActualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTRentaActualKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n')//al presionar enter se pasa a la siguiente caja y se inhabilita la anterior
        {
            ManipulaInterfaces.cambiar(jDFechaRentaActual);
            ManipulaInterfaces.habilita(jTRentaActual, false);
        }
    }//GEN-LAST:event_jTRentaActualKeyPressed

    private void jTRentaActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTRentaActualKeyTyped
        // TODO add your handling code here:
        Validaciones.flotante(evt);//valida que solo se acepten flotantes
    }//GEN-LAST:event_jTRentaActualKeyTyped

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        int r = this.validaCamposVacios();//llamamos al metodo validaCamposVacios
        if (r == 0)//entra si los campos no regresan un 1, quiere decir que no vienen vacios
        {
            //obtenemos la fecha del jDateChooser
            String sFechaRentaActual = new SimpleDateFormat("yyyy-MM-dd").format(jDFechaRentaActual.getDate());
            System.out.println(sFechaRentaActual);

            Conexion con = new Conexion();
            con.Conecta("localhost", "trajin", "root", "123456");//conexión con BD
            if (con.con != null)
            {
                String s = "null," + "null," + "null," + "" + jTRentaActual.getText() + "" + ",'" +sFechaRentaActual + "'";
                Querys q = new Querys();
                q.Insertar(con.con, "rentasparametros", s);

                try
                {
                    con.con.close();
                    Mensajes.exito(this);

                } catch (Exception ex)
                {
                    Mensajes.msj(this, "Error en DB... " + ex.getMessage());
                }
            }
            CancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void AceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AceptarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n')
        {
            AceptarActionPerformed(null);
        }
    }//GEN-LAST:event_AceptarKeyPressed

    private void AceptarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AceptarKeyTyped

    }//GEN-LAST:event_AceptarKeyTyped

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        //si da clic en cancelar, limpia las cajas y se posiciona en la primer caja de texto
        jDFechaRentaActual.setCalendar(null);
        ManipulaInterfaces.limpia(jTRentaActual);
        ManipulaInterfaces.habilita(jTRentaActual, true);
        ManipulaInterfaces.habObjetos(false, jDFechaRentaActual);
        jTRentaActual.requestFocus();
        //dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void CancelarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CancelarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarKeyTyped

    private void jDFechaRentaActualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDFechaRentaActualKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            if (jDFechaRentaActual.getDate() == null) {
                ManipulaInterfaces.cambiar(Aceptar);
                ManipulaInterfaces.habilita(jDFechaRentaActual, false);
            }
        }
    }//GEN-LAST:event_jDFechaRentaActualKeyPressed

    private void jDFechaRentaActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDFechaRentaActualKeyTyped
        // TODO add your handling code here:
        Validaciones.cadena(evt);
    }//GEN-LAST:event_jDFechaRentaActualKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAltaRentasParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAltaRentasParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAltaRentasParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAltaRentasParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pantallaAltaRenta.setTitle("Alta de Parametros Renta");
                pantallaAltaRenta.setLocationRelativeTo(null);
                pantallaAltaRenta.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private com.toedter.calendar.JDateChooser jDFechaRentaActual;
    private javax.swing.JLabel jLFeRenActu;
    private javax.swing.JLabel jLRPR;
    private javax.swing.JLabel jLRenActu;
    private javax.swing.JTextField jTRentaActual;
    // End of variables declaration//GEN-END:variables
}
