 /* Techno Engineers
 * Registro de rentas
 * 23/04/2016 -- 
 * Registro de cuadros: 
 * Sirve para dar de alta a las rentas 
 * Numero de metodos en el código: 
 * Interfaces: 
 */
package tr.rentas;

import vista.mensajes.Mensajes;
/**
 *
 * @author JordanTrujillo
 */
public class RentasParametros extends javax.swing.JFrame {

    /**
     * Creates new form RentasParametros
     */
    public RentasParametros() {
        initComponents();
        
    }
    public int validaCamposVacios()
    {
        if (rentaActualRentasParametros.getText().equals(""))
        {
            Mensajes.falla(this, "Escribe una cantidad de renta valida");
            rentaActualRentasParametros.requestFocus();
            return 1;
        } 
        return 0;
    }
    private void consutaRenta(){
        Conexion con = new Conexion();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rentaActualRentasParametros = new javax.swing.JTextField();
        fechaRentaActualRentasParametros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RegistrarRenta = new javax.swing.JButton();
        CancelarRenta = new javax.swing.JButton();
        rentaAnteriorRentasParametros = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fechaRentaAnteriorRentasParametros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Rentas");

        rentaActualRentasParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentaActualRentasParametrosActionPerformed(evt);
            }
        });

        fechaRentaActualRentasParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaRentaActualRentasParametrosActionPerformed(evt);
            }
        });

        jLabel5.setText("Renta actual");

        jLabel6.setText("Fecha de renta actual");

        RegistrarRenta.setBackground(new java.awt.Color(51, 153, 255));
        RegistrarRenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RegistrarRenta.setText("Registrar Renta");
        RegistrarRenta.setPreferredSize(new java.awt.Dimension(91, 25));
        RegistrarRenta.setSize(new java.awt.Dimension(91, 25));
        RegistrarRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarRentaActionPerformed(evt);
            }
        });

        CancelarRenta.setBackground(new java.awt.Color(51, 153, 255));
        CancelarRenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CancelarRenta.setText("Cancelar Renta");
        CancelarRenta.setPreferredSize(new java.awt.Dimension(91, 25));
        CancelarRenta.setSize(new java.awt.Dimension(91, 25));
        CancelarRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarRentaActionPerformed(evt);
            }
        });

        rentaAnteriorRentasParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentaAnteriorRentasParametrosActionPerformed(evt);
            }
        });

        jLabel3.setText("Renta Anterior");

        fechaRentaAnteriorRentasParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaRentaAnteriorRentasParametrosActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha de renta anterior");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(RegistrarRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fechaRentaAnteriorRentasParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rentaAnteriorRentasParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CancelarRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fechaRentaActualRentasParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rentaActualRentasParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)))))))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentaAnteriorRentasParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaRentaAnteriorRentasParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentaActualRentasParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaRentaActualRentasParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentaAnteriorRentasParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentaAnteriorRentasParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentaAnteriorRentasParametrosActionPerformed

    private void rentaActualRentasParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentaActualRentasParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentaActualRentasParametrosActionPerformed

    private void fechaRentaAnteriorRentasParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaRentaAnteriorRentasParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaRentaAnteriorRentasParametrosActionPerformed

    private void fechaRentaActualRentasParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaRentaActualRentasParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaRentaActualRentasParametrosActionPerformed

    private void RegistrarRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarRentaActionPerformed
        // TODO add your handling code here:
        int r = this.validaCamposVacios();
        if (r == 0)
        {
            Conexion objConexion = new Conexion();
            objConexion.Conecta("localhost", "trajin", "root", "");
            if (objConexion.con != null)
            {
                String sCadena = ""+","+rentaAnteriorRentasParametros.getText()+","+"'"+fechaRentaAnteriorRentasParametros.getText()+"'"+","+ rentaActualRentasParametros.getText() +","+"'"+fechaRentaActualRentasParametros.getText()+"'";
                Querys objQuerys = new Querys();
                objQuerys.Insertar(objConexion.con, "rentasparametros", sCadena);

                try
                {
                    objConexion.con.close();
                    Mensajes.exito(this);

                } catch (Exception ex)
                {
                    Mensajes.msj(this, "Error en DB... " + ex.getMessage());
                }
            }
            CancelarRentaActionPerformed(evt);
        }
    }//GEN-LAST:event_RegistrarRentaActionPerformed

    private void CancelarRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarRentaActionPerformed
        // TODO add your handling code here:
        ManipulaInterfaces.habObjetos(false, RegistrarRenta);
        ManipulaInterfaces.limpia(rentaActualRentasParametros);
        rentaActualRentasParametros.requestFocus();
    }//GEN-LAST:event_CancelarRentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentasParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentasParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentasParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentasParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentasParametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarRenta;
    private javax.swing.JButton RegistrarRenta;
    private javax.swing.JTextField fechaRentaActualRentasParametros;
    private javax.swing.JTextField fechaRentaAnteriorRentasParametros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rentaActualRentasParametros;
    private javax.swing.JTextField rentaAnteriorRentasParametros;
    // End of variables declaration//GEN-END:variables
}
